FROM ubuntu:20.04

# Install necessary packages
RUN apt-get update && apt-get install -y \
    openjdk-8-jdk \
    ssh \
    rsync \
    wget \
    sudo \
    bash

# Create Hadoop user and set password
RUN useradd -m -s /bin/bash hadoop && echo "hadoop:hadoop" | chpasswd && adduser hadoop sudo

# Download and extract Hadoop
RUN wget https://downloads.apache.org/hadoop/common/hadoop-3.3.6/hadoop-3.3.6.tar.gz && \
    tar -xzvf hadoop-3.3.6.tar.gz -C /usr/local/ && \
    mv /usr/local/hadoop-3.3.6 /usr/local/hadoop && \
    chown -R hadoop:hadoop /usr/local/hadoop

# Set up SSH for Hadoop user
RUN mkdir -p /home/hadoop/.ssh && \
    ssh-keygen -t rsa -P "" -f /home/hadoop/.ssh/id_rsa && \
    cat /home/hadoop/.ssh/id_rsa.pub >> /home/hadoop/.ssh/authorized_keys && \
    chmod 0600 /home/hadoop/.ssh/authorized_keys && \
    chown -R hadoop:hadoop /home/hadoop/.ssh

# Copy Hadoop configuration files
COPY core-site.xml /usr/local/hadoop/etc/hadoop/
COPY hdfs-site.xml /usr/local/hadoop/etc/hadoop/
COPY mapred-site.xml /usr/local/hadoop/etc/hadoop/
COPY yarn-site.xml /usr/local/hadoop/etc/hadoop/

# Set environment variables
ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
ENV HADOOP_HOME=/usr/local/hadoop
ENV PATH=$PATH:$HADOOP_HOME/bin:$HADOOP_HOME/sbin:$JAVA_HOME/bin

# Add environment variables to hadoop user's .bashrc
RUN echo "export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64" >> /home/hadoop/.bashrc && \
    echo "export HADOOP_HOME=/usr/local/hadoop" >> /home/hadoop/.bashrc && \
    echo "export PATH=\$PATH:\$HADOOP_HOME/bin:\$HADOOP_HOME/sbin:\$JAVA_HOME/bin" >> /home/hadoop/.bashrc

# Add environment variables to /etc/environment for global availability
RUN echo "JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64" >> /etc/environment && \
    echo "HADOOP_HOME=/usr/local/hadoop" >> /etc/environment && \
    echo "PATH=$PATH:$HADOOP_HOME/bin:$HADOOP_HOME/sbin:$JAVA_HOME/bin" >> /etc/environment

# Fix permissions for Hadoop logs
RUN mkdir -p /usr/local/hadoop/logs && chown -R hadoop:hadoop /usr/local/hadoop/logs

# Format HDFS namenode
RUN /bin/bash -c "source /home/hadoop/.bashrc && /usr/local/hadoop/bin/hdfs namenode -format"

# Prepare to run SSH and Hadoop services
RUN mkdir -p /run/sshd && chmod 0755 /run/sshd
RUN echo "hadoop ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# Set working directory
WORKDIR /home/hadoop

# Start SSH and Hadoop services
CMD ["/usr/sbin/sshd", "-D"]
