# Usa la imagen oficial de PostgreSQL desde Docker Hub
FROM postgres:latest

# Variables de entorno para configurar la base de datos
ENV POSTGRES_DB=mydatabase
ENV POSTGRES_USER=myuser
ENV POSTGRES_PASSWORD=mypassword

VOLUME [ "/var/lib/postgresql/data" ]

# Copia los scripts SQL para inicializar la base de datos
COPY init.sql /docker-entrypoint-initdb.d/

