Select * from INE_DISTRITO_2020;

SELECT NOM_ENT
FROM INE_DISTRITO_2020
WHERE PCON_DISC BETWEEN 18500 AND 30500;

UPDATE INE_DISTRITO_2020
SET NOM_ENT = 'Caracolandia'
WHERE NOM_ENT = 'Quinatan Roo';

SELECT * FROM INE_DISTRITO_2020
WHERE NOM_ENT = 'Caracolandia'

SELECT DISTINCT NOM_ENT FROM INE_DISTRITO_2020

UPDATE INE_DISTRITO_2020
SET NOM_ENT = 'Ciudad de México'
WHERE NOM_ENT like 'Ciudad de M%';

UPDATE INE_DISTRITO_2020
SET NOM_ENT = 'Michoacán de Ocampo'
WHERE NOM_ENT like 'Michoac%';

UPDATE INE_DISTRITO_2020
SET NOM_ENT = 'México'
WHERE NOM_ENT like 'M%xico';

UPDATE INE_DISTRITO_2020
SET NOM_ENT = 'Nuevo León'
WHERE NOM_ENT like 'Nuevo Le%n';

UPDATE INE_DISTRITO_2020
SET NOM_ENT = 'Querétaro'
WHERE NOM_ENT like 'Quer%';

UPDATE INE_DISTRITO_2020
SET NOM_ENT = 'Yucatán'
WHERE NOM_ENT like 'Yucat%n';

UPDATE INE_DISTRITO_2020
SET NOM_ENT = 'San Luis Potosí'
WHERE NOM_ENT like 'San Luis%';



UPDATE INE_DISTRITO_2020
SET COMPLEJIDA = 'Concentración Media'
WHERE COMPLEJIDA like 'Concentraci%n Media';

Select * from INE_DISTRITO_2020;


SELECT DISTINCT COMPLEJIDA FROM INE_DISTRITO_2020

Altamente Concentrado 1
Altamente Concentrado 2
Concentración Media
Concentrado 1
Concentrado 2
Disperso 1
Disperso 2
Muy Disperso 1
Muy Disperso 2

ALTER TABLE dbo.INE_DISTRITO_2020
ADD ALT_CON_1 INT, ALT_CON_2 INT, CON_MED INT, CON1 INT, CON2 INT, DIS1 INT, DIS2 INT, MDIS_1 INT, MDIS_2 INT;