-- Detailed description comment: Query_1
SELECT * FROM INEGI.dbo.INE_DISTRITO_2020;


-- Detailed description comment: Query_2
SELECT NOM_ENT
FROM INEGI.dbo.INE_DISTRITO_2020
WHERE PCON_DISC BETWEEN 18500 AND 30500;

-- Detailed description comment: Query_3
UPDATE INEGI.dbo.INE_DISTRITO_2020
SET NOM_ENT = 'Caracolandia'
WHERE NOM_ENT = 'Quintana Roo';

SELECT * FROM INEGI.dbo.INE_DISTRITO_2020
WHERE NOM_ENT = 'Caracolandia'

-- Detailed description comment: Query_4
UPDATE INEGI.dbo.INE_DISTRITO_2020
SET NOM_ENT = 'Ciudad de México'
WHERE NOM_ENT LIKE 'Ciudad de M%';

UPDATE INEGI.dbo.INE_DISTRITO_2020
SET NOM_ENT = 'Michoacán de Ocampo'
WHERE NOM_ENT LIKE 'Michoac%';

UPDATE INEGI.dbo.INE_DISTRITO_2020
SET NOM_ENT = 'México'
WHERE NOM_ENT LIKE 'M%xico';

UPDATE INEGI.dbo.INE_DISTRITO_2020
SET NOM_ENT = 'Nuevo León'
WHERE NOM_ENT LIKE 'Nuevo Le%n';

UPDATE INEGI.dbo.INE_DISTRITO_2020
SET NOM_ENT = 'Querétaro'
WHERE NOM_ENT LIKE 'Quer%';

UPDATE INEGI.dbo.INE_DISTRITO_2020
SET NOM_ENT = 'Yucatán'
WHERE NOM_ENT LIKE 'Yucat%n';

UPDATE INEGI.dbo.INE_DISTRITO_2020
SET NOM_ENT = 'San Luis Potosí'
WHERE NOM_ENT LIKE 'San Luis%';

SELECT DISTINCT NOM_ENT FROM INEGI.dbo.INE_DISTRITO_2020

-- Detailed description comment: Query_5
UPDATE INEGI.dbo.INE_DISTRITO_2020
SET COMPLEJIDA = 'Concentración Media'
WHERE COMPLEJIDA LIKE 'Concentraci%n Media';

SELECT * FROM INEGI.dbo.INE_DISTRITO_2020 WHERE COMPLEJIDA = 'Concentración Media';

-- Detailed description comment: Query_6
SELECT DISTINCT COMPLEJIDA FROM INEGI.dbo.INE_DISTRITO_2020;

-- Altamente Concentrado 1
-- Altamente Concentrado 2
-- Concentración Media
-- Concentrado 1
-- Concentrado 2
-- Disperso 1
-- Disperso 2
-- Muy Disperso 1
-- Muy Disperso 2

-- Detailed description comment: Query_7
ALTER TABLE INEGI.dbo.INE_DISTRITO_2020
ADD ALT_CON_1 INT, ALT_CON_2 INT, CON_MED INT, CON1 INT, CON2 INT, DIS1 INT, DIS2 INT, MDIS_1 INT, MDIS_2 INT;


-- Detailed description comment: Query_8
UPDATE INEGI.dbo.INE_DISTRITO_2020
SET ALT_CON_1 = 1
WHERE COMPLEJIDA = 'Altamente Concentrado 1';

UPDATE INEGI.dbo.INE_DISTRITO_2020
SET ALT_CON_2 = 1
WHERE COMPLEJIDA = 'Altamente Concentrado 2';

UPDATE INEGI.dbo.INE_DISTRITO_2020
SET CON_MED = 1
WHERE COMPLEJIDA = 'Concentración Media';

UPDATE INEGI.dbo.INE_DISTRITO_2020
SET CON1 = 1
WHERE COMPLEJIDA = 'Concentrado 1';

UPDATE INEGI.dbo.INE_DISTRITO_2020
SET CON2 = 1
WHERE COMPLEJIDA = 'Concentrado 2';

UPDATE INEGI.dbo.INE_DISTRITO_2020
SET DIS1 = 1
WHERE COMPLEJIDA = 'Disperso 1';

UPDATE INEGI.dbo.INE_DISTRITO_2020
SET DIS2 = 1
WHERE COMPLEJIDA = 'Disperso 2';

UPDATE INEGI.dbo.INE_DISTRITO_2020
SET MDIS_1 = 1
WHERE COMPLEJIDA = 'Muy Disperso 1';

UPDATE INEGI.dbo.INE_DISTRITO_2020
SET MDIS_2 = 1
WHERE COMPLEJIDA = 'Muy Disperso 2';

SELECT ALT_CON_1, COMPLEJIDA FROM INEGI.dbo.INE_DISTRITO_2020 WHERE ALT_CON_1 = 1;