# Usa la imagen oficial de PostgreSQL desde Docker Hub
FROM postgres:latest

# Variables de entorno para configurar la base de datos
ENV POSTGRES_DB=generaldb
ENV POSTGRES_USER=jason
ENV POSTGRES_PASSWORD=jason

VOLUME [ "/var/lib/postgresql/data" ]

# Copia los scripts SQL para inicializar la base de datos
COPY init.sql /docker-entrypoint-initdb.d/

